---
name: actions
on:
  push:
    tags-ignore:
      - '**'
    branches:
      - main
  pull_request:

jobs:

  golangci-lint:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v8.0.0
